### ISSUE TITLE
BUG-1. 201 OK при передаче пустого password в PATCH /users/{userId} запрос

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#19]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.0.0
## URL стенда
http://195.161.68.231:8080 

## Приоритет
High
## Критичность
Critical
## Описание
При передаче пустого обязательного поля password в PATCH /users/{userId} запросе приходит ответ 200 OK вместо ошибки 400
### Предусловие
Создать пользователя запросом POST http://195.161.68.231:8080/users 
{
  "name": "Андрей",
  "surname": "Андреев",
  "login": "andrew",
  "password": "password",
  "email": "j@mail.ru",
  "dateBirth": "1999-09-14",
  "avatarUrl": "https://habr.com/ru/and.jpg"
}

### Шаги
1.	Отправить PATCH /users/{userId} запрос ({userId} - созданного пользователя) с body
{
  "name": "Андрей",
  "surname": "Андреев",
  "login": "andrew",
  "password": "",
  "email": "j@mail.ru",
  "dateBirth": "1999-09-14",
  "avatarUrl": "https://habr.com/ru/and.jpg"
}

Curl: 
curl --location --request PATCH 'http://195.161.68.231:8080/users/7' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "Андрей",
  "surname": "Андреев",
  "login": "andrew",
  "password": "",
  "email": "j@mail.ru",
  "dateBirth": "1999-09-14",
  "avatarUrl": "https://habr.com/ru/and.jpg"
}'

### Ожидаемый результат
{"status": "BAD_REQUEST","message": "Пароль не должен быть пустым","date": "2023-09-11 19:06:04"} 
### Фактический результат
200 OK
{
    "idUser": 7,
    "name": "Андрей",
    "surname": "Андреев",
    "login": "andrew",
    "email": "j@mail.ru",
    "dateBirth": "1999-09-14",
    "avatarUrl": "https://habr.com/ru/and.jpg"
}

## Дополнительно: скрины, логи

![Image](https://user-images.githubusercontent.com/138881802/267661982-6e5b2d3f-63d0-4fda-b8b7-b48a2d393386.png)

**Comment by Valentina810** [comment]
Добавлено в документацию. 
При обновлении пользователя решили что если с фронта приходит пароль - то игнорировать это и в БД пароль не менять. Менем пароль только в том случае, если пароль приходит не пустой, поэтому при редактировании допускается сейчас присылать пустой пароль.

**Comment by Valentina810** [comment]
Прилинкован https://github.com/Valentina810/lms/pull/20
При  PATCH допускается пустой пароль
