### ISSUE TITLE
BUG-3. 400 BAD REQUEST при вводе 75 и более символов в email при отправке запроса POST /users

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#22]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
Medium
## Критичность
Major
## Описание
Поле email принимает до 250 символов согласно требованиям, но при вводе 75 и более символов появляется ошибка, что у поля неправильный формат
### Шаги
Отправить запрос POST /users на создание пользователя, в body указать:

{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}

curl --location 'http://195.161.68.231:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}'

### Ожидаемый результат
201 CREATED
{"id":"1",
"name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}
### Фактический результат
400 BAD REQUEST
{
    "status": "BAD_REQUEST",
    "message": "Email должна иметь правильный формат. Пример ivan@yandex.ru или petr@gmail.com; ",
    "date": "2023-09-14 19:02:46"
}

**Comment by Yudiol** [comment]
Вопрос решили

**Comment by Valentina810** [comment]
Обновлена документация, прилинкован https://github.com/Valentina810/lms/pull/41

**Comment by janekomarovskaja** [comment]
Протестировано, работает
