### ISSUE TITLE
BUG-2. Отсутствует корректное сообщение об ошибке при отправке body c некорректной структурой в запросе POST /users

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#23]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
low
## Критичность
trivial
## Ссылка на ТК (если есть)
https://docs.google.com/spreadsheets/d/1uZvrsg0FlwcaEs_8QjwqR4Y30nDS6iXhEKmZsSqvBKs/edit#gid=0&range=A35:H37
### Шаги
Отправить запрос POST /users на создание пользователя, в body указать
{
  "name": "string"
  "surname": "string"
  "login": "string"
  "password": "string"
  "email": "j@mail.ru"
  "dateBirth": "1999-09-14"
  "avatarUrl": "string"
}

### Ожидаемый результат
В ответе указание ошибки
{"status": "BAD_REQUEST","message": "Неверная структура объекта: проверьте скобки, запятые и названия полей","date": "2023-09-11 19:06:04"} 
### Фактический результат
{
    "status": "BAD_REQUEST",
    "message": "JSON parse error: Unexpected character ('\"' (code 34)): was expecting comma to separate Object entries",
    "date": "2023-09-14 18:50:44"
}

**Comment by Yudiol** [comment]
Починил

**Comment by Valentina810** [comment]
Прилинкован https://github.com/Valentina810/lms/pull/43

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
