### ISSUE TITLE
BUG-4 201 CREATED при передаче параметров типа string в виде number при отправке запроса POST /users (для всех полей, кроме email)

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#24]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет

High

## Критичность
major
## Описание
При передаче параметров типа string в виде number в ответе данные преображаются в string (для всех полей, кроме email), а dateBirth - в случайную дату.
### Шаги
Отправить запрос POST /users на создание пользователя, в body указать:
{
  "name": 1234,
  "surname": 1234,
  "login": 1234,
  "password": 1234,
  "email": "1@mail.ru",
  "dateBirth": 1234,
  "avatarUrl": 1234
}

curl --location 'http://195.161.68.231:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": 1234,
  "surname": 1234,
  "login": 1234,
  "password": 1234,
  "email": "1@mail.ru",
  "dateBirth": 1234,
  "avatarUrl": 1234
}'

### Ожидаемый результат
400 BAD REQUEST
### Фактический результат
201 CREATED
{
    "idUser": 23,
    "name": "1234",
    "surname": "1234",
    "login": "1234",
    "email": "1@mail.ru",
    "dateBirth": "1973-05-19",
    "avatarUrl": "1234"
}

**Comment by Yudiol** [comment]
name и surname добавил проверку теперь принимает только буквы
login и password  оставляем так
email проверка есть

dateBirth  и avatarUrl в разработке

**Comment by Yudiol** [comment]
avatarUrl сделал, проверяет что бы в начале было https:// или http://

**Comment by Yudiol** [comment]
dateBirth поверку написал
Пока вопрос закрыт, нужно выложить и проверять

**Comment by Valentina810** [comment]
По дате пока в работе вопрос, надо подробнее изучить стандартные валидации, чтобы не писать костыли

**Comment by Valentina810** [comment]
По дате сделали в рамках https://github.com/Valentina810/lms/pull/76 - пропускает только строку по определённому формату "\\d{4}-\\d{2}-\\d{2}", валидирует что это действительная дата. Но нет ограничений на верхнюю/нижнюю дату, так как в требованиях этого не описано.

**Comment by janekomarovskaja** [comment]
Протестировано повторно, всё ок
