### ISSUE TITLE
BUG-8 200 OK при передаче несуществующего userId в запросе GET /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#25]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080
## Приоритет
medium
## Критичность
major
## Ссылка на ТК
https://docs.google.com/spreadsheets/d/1uZvrsg0FlwcaEs_8QjwqR4Y30nDS6iXhEKmZsSqvBKs/edit#gid=1673173674&range=A11:G13

### Шаги
Отправить запрос GET /users/{userId}/lessons с указанием несуществующего userId

### Ожидаемый результат
404 NOT FOUND

в теле ответа вернулась причина ошибки
{"status": "NOT_FOUND","message": "Пользователь c id не найден ","date": "2023-09-11 19:06:04"}

### Фактический результат
200 OK
body: []

**Comment by Valentina810** [comment]
Исправлено https://github.com/Valentina810/lms/pull/81

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
