### ISSUE TITLE
BUG-9 500 Internal Server Error при передаче "idSubject": null в запросе POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#26]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
minor
## Ссылка на ТК
https://docs.google.com/spreadsheets/d/1uZvrsg0FlwcaEs_8QjwqR4Y30nDS6iXhEKmZsSqvBKs/edit#gid=223522153&range=A30:G32
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}
'
### Ожидаемый результат
400 Bad request

{
"status": "BAD_REQUEST",
"message": "Id предмета обязателен для заполнения; ",
"date": "2023-09-13 19:47:53"
}

### Фактический результат
500 Internal Server Error
{
    "timestamp": "2023-09-15T14:56:15.329+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/users/3/lessons"
}

**Comment by Valentina810** [comment]
исправлено https://github.com/Valentina810/lms/pull/87

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
