### ISSUE TITLE
BUG-10 500 Internal Server Error при передаче более 500 символов в topic в запросе POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#28]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
minor
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
  "subject": {
    "idSubject": 2
  },
  "topic": "Предлоги", /ввести 501 символ
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
  "subject": {
    "idSubject": 2
  },
  "topic": "topictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopictopicc",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "url",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}
'

### Ожидаемый результат
400 Bad request

 {
"status": "BAD_REQUEST",
"message": "Тема урока должна быть не больше 500 знаков; ",
"date": "2023-09-13 19:55:12"
}

### Фактический результат
500 Internal Server Error
{
    "timestamp": "2023-09-15T15:42:26.241+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/users/3/lessons"
}

**Comment by Valentina810** [comment]
Добавлена валидация на поле topic, пр https://github.com/Valentina810/lms/pull/64

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
