### ISSUE TITLE
BUG-13 В поле homeworkUrl нельзя передать более 100 символов в запросе POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#30]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
major
## Описание
В поле homeworkUrl можно передать не более 100 символов, по требованиям не более 1000
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги", 
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm", 
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm", 
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm", //ввести 101 символ
  "progress": 0,
  "checkSuccessfully": false
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
  "subject": {
    "idSubject": 2
  },
  "topic": "Предлоги",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/theoryUrltheoryUrltheoryUrltheoryUrltheoryUrltheoryUrltheoryUrltheoryUrlurlur.com",
  "progress": 0,
  "checkSuccessfully": false
}'
### Ожидаемый результат
201 CREATED

### Фактический результат
{
    "status": "BAD_REQUEST",
    "message": "Длина адреса должна быть не больше 1000 знаков; ",
    "date": "2023-09-15 18:23:36"
}

**Comment by Valentina810** [comment]
Пофикшен https://github.com/Valentina810/lms/pull/69

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
