### ISSUE TITLE
BUG-14  Некорректный текст ошибки при передаче значений больше 100 для progress в запросе POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#32]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
trivial
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
    "subject": {
        "idSubject": 4
    },
    "topic": "тема",
    "date": "2024-09-16",
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
    "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
    "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
    "progress": 101,
    "checkSuccessfully": true
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
    "subject": {
        "idSubject": 4
    },
    "topic": "тема",
    "date": "2024-09-16",
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
    "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
    "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
    "progress": 101,
    "checkSuccessfully": true
}'

### Ожидаемый результат
тело ответа:
{
"status": "BAD_REQUEST",
"message": "Прогресс должен быть числом от 0 до 100; ",
"date": "2023-09-11 19:06:04"
}

### Фактический результат
тело ответа:
{
    "status": "BAD_REQUEST",
    "message": "must be less than or equal to 100; ",
    "date": "2023-09-16 17:31:48"
}

**Comment by Valentina810** [comment]
Пофикшен https://github.com/Valentina810/lms/pull/69

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
