### ISSUE TITLE
BUG-15 Некорректный текст ошибки при передаче несуществующего userId в запросе PATCH /users/{userId}/lessons/{lessonId}

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#33]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
minor
### Шаги
Отправить запрос PATCH /users/{userId}/lessons/{lessonId}, в userId указать несуществующее id пользователя
{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги", 
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm", 
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm", 
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm", //ввести 101 символ
  "progress": 0,
  "checkSuccessfully": false
}

### Ожидаемый результат
тело ответа:
{
"status": "NOT_FOUND",
"message": "Пользователь c id 10 не найден ",
"date": "2023-09-11 19:06:04"
}
### Фактический результат
тело ответа:
{
    "status": "NOT_FOUND",
    "message": "Урок c id=40 не найден.",
    "date": "2023-09-16 19:37:25"
}

**Comment by Valentina810** [comment]
Измена логика в updateLesson https://github.com/Valentina810/lms/pull/85
