### ISSUE TITLE
BUG-16 500 Internal Server Error при передаче "idSubject": null в запросе PATCH /users/{userId}/lessons/{lessonId}

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#34]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
minor
### Предусловия
1) Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

2) Отправить POST /users/{userId}/lessons запрос

{
  "subject": {
    "idSubject": 2
  },
  "topic": "Предлоги",
  "date": "2023-09-14",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}

### Шаги
Отправить запрос PATCH /users/{userId}/lessons/{lessonId}
{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}

curl --location --request PATCH 'http://195.161.68.231:8080/users/3/lessons/40' \
--header 'Content-Type: application/json' \
--data '{
  "subject": {
    "idSubject": null
  },
  "topic": "Предлоги",
  "date": "2023-09-20",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}'

### Ожидаемый результат
400 Bad request

{
"status": "BAD_REQUEST",
"message": "Id предмета обязателен для заполнения; ",
"date": "2023-09-13 19:47:53"
}

### Фактический результат
{
    "timestamp": "2023-09-16T19:55:10.967+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/users/3/lessons/40"
}

**Comment by Valentina810** [comment]
исправлено https://github.com/Valentina810/lms/pull/87

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
