### ISSUE TITLE
BUG-6. 400 BAD REQUEST при вводе 75 и более символов в email при отправке запроса PATCH /users/{userId}

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/lms#39]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
Medium
## Критичность
Major
## Описание
Поле email принимает до 250 символов согласно требованиям, но при вводе 75 и более символов появляется ошибка, что у поля неправильный формат
## Предусловие
Отправить запрос PATCH /users/{userId} на редактирование данных пользователя. {userId} - id созданного пользователя. В body указать
{
"name": "string"
"surname": "string"
"login": "string"
"password": "string"
"email": "[j@mail.ru](mailto:j@mail.ru)"
"dateBirth": "1999-09-14"
"avatarUrl": "string"
}

### Шаги
Отправить запрос PATCH /users/{userId} на редактирование пользователя, в body указать:

{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}

curl --location --request PATCH 'http://195.161.68.231:8080/users/7' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}'

### Ожидаемый результат
200 OK
{"id":"1",
"name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasavirinasavirinasavirinasavirinasavirinasavirinasavirinasavi@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}
### Фактический результат
400 BAD REQUEST
{
    "status": "BAD_REQUEST",
    "message": "Email должна иметь правильный формат. Пример ivan@yandex.ru или petr@gmail.com; ",
    "date": "2023-09-14 19:02:46"
}

**Comment by Valentina810** [comment]
Обновлена документация, прилинкован https://github.com/Valentina810/lms/pull/41

**Comment by janekomarovskaja** [comment]
Протестировано, работает
