### ISSUE TITLE
BUG-5. Отсутствует корректное сообщение об ошибке при отправке body c некорректной структурой в запросе PATCH /users/{userId}

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/lms#42]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
low
## Критичность
trivial
## Предусловие
Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

### Шаги
Отправить запрос PATCH /users/{userId} на редактирование данных  пользователя. {userId} - id созданного пользователя. В body указать
{
  "name": "string"
  "surname": "string"
  "login": "string"
  "password": "string"
  "email": "j@mail.ru"
  "dateBirth": "1999-09-14"
  "avatarUrl": "string"
}

### Ожидаемый результат
В ответе указание ошибки
{"status": "BAD_REQUEST","message": "Неверная структура объекта: проверьте скобки, запятые и названия полей","date": "2023-09-11 19:06:04"} 

### Фактический результат
{
    "status": "BAD_REQUEST",
    "message": "JSON parse error: Unexpected character ('\"' (code 34)): was expecting comma to separate Object entries",
    "date": "2023-09-14 18:50:44"
}

**Comment by Valentina810** [comment]
Пофикшено, прилинкован https://github.com/Valentina810/lms/pull/43

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
