### ISSUE TITLE
BUG-7. 200 OK при передаче параметров типа string в виде number при отправке запроса PATCH /users/{userId} (для всех полей, кроме email)

### ISSUE THREAD

**Issue by Valentina810** [Valentina810/lms#44]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет

medium

## Критичность
major
## Описание
При передаче параметров типа string в виде number в ответе данные преображаются в string (для всех полей, кроме email), а dateBirth - в случайную дату.
## Предусловие
Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

### Шаги
Отправить запрос PATCH /users/{userId} на редактирование данных пользователя. {userId} - id созданного пользователя. В body указать
{
  "name": 1234,
  "surname": 1234,
  "login": 1234,
  "password": 1234,
  "email": "1@mail.ru",
  "dateBirth": 1234,
  "avatarUrl": 1234
}

### Ожидаемый результат
400 BAD REQUEST
### Фактический результат
200 OK
{
    "idUser": 23,
    "name": "1234",
    "surname": "1234",
    "login": "1234",
    "email": "1@mail.ru",
    "dateBirth": "1973-05-19",
    "avatarUrl": "1234"
}

**Comment by Valentina810** [comment]
Дубликат, пификшен в https://github.com/Valentina810/lms/pull/57

**Comment by Valentina810** [comment]
Надо поискать информацию о валидации на то что в поле приходит именно строка, котрую можно преобразовать в дату по шаблону

**Comment by Valentina810** [comment]
По дате сделали в рамках https://github.com/Valentina810/lms/pull/76 - пропускает только строку по определённому формату "\d{4}-\d{2}-\d{2}", валидирует что это действительная дата. Но нет ограничений на верхнюю/нижнюю дату, так как в требованиях этого не описано.

**Comment by Yudiol** [comment]
Мы же обсуждали этот момент, ты сказала что у нас нет ограничений по верху и по низу, если мы говорим про dateBirth

**Comment by Valentina810** [comment]
Вроде я так и написала, что из-за того что в требованиях нет, мы и не делали

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
