### ISSUE TITLE
BUG-25 Некорректный тест ошибки при передаче несуществующих userId и lessonId в запросе GET /users/{userId}/lessons/{lessonId}

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#51]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080
## Приоритет
medium
## Критичность
trivial 

### Шаги
Отправить запрос GET /users/{userId}/lessons/{lessonId}

userId и lessonId - несуществующие

curl --location 'http://195.161.68.231:8080/users/100/lessons/100'

### Ожидаемый результат
404 NOT FOUND

{
"status": "NOT_FOUND",
"message": "У пользователя с id 1 не найден урок с id 1",
"date": "2023-09-11 19:06:04"
}

### Фактический результат
{
    "status": "NOT_FOUND",
    "message": "Урок c id=100 не найден.",
    "date": "2023-09-17 11:04:12"
}

**Comment by Valentina810** [comment]
Исправно https://github.com/Valentina810/lms/pull/81

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
