### ISSUE TITLE
BUG-26 Некорректный тест ошибки при передаче несуществующего userId в запросе DELETE /users/{userId}/lessons/{lessonId}

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#52]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080
## Приоритет
medium
## Критичность
trivial 

## Предусловие
1) Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

2) Отправить POST /users/{userId}/lessons запрос

{
  "subject": {
    "idSubject": 2
  },
  "topic": "Предлоги",
  "date": "2023-09-14",
  "timeStart": "09:40:00",
  "timeEnd": "09:40:00",
  "theoryUrl": "https://habr.com/ru/theoryUrl.htm",
  "practiceUrl": "https://habr.com/ru/practiceUrl.htm",
  "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
  "progress": 0,
  "checkSuccessfully": false
}

### Шаги
Отправить запрос DELETE /users/{userId}/lessons/{lessonId}

userId- несуществующий

curl --location --request DELETE 'http://195.161.68.231:8080/users/300/lessons/29'

### Ожидаемый результат
404 NOT FOUND

{
"status": "NOT_FOUND",
"message": "Пользователь c id 10 не найден ",
"date": "2023-09-11 19:06:04"
}

### Фактический результат
{
    "status": "NOT_FOUND",
    "message": "Урок c id=29 не найден.",
    "date": "2023-09-17 11:11:47"
}

**Comment by Valentina810** [comment]
Добавлено сообщение при отсутствии пользователя https://github.com/Valentina810/lms/pull/83
