### ISSUE TITLE
BUG-26 201 CREATED при передаче параметров типа string в виде number в запросе POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#53]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
major
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
    "subject": {
        "idSubject": 4
    },
    "topic": 123,
    "date": 123,
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": 123,
    "practiceUrl": 123,
    "homeworkUrl": 123,
    "progress": 100,
    "checkSuccessfully": true
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
    "subject": {
        "idSubject": 4
    },
    "topic": 123,
    "date": 123,
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": 123,
    "practiceUrl": 123,
    "homeworkUrl": 123,
    "progress": 100,
    "checkSuccessfully": true
}'

### Ожидаемый результат
400 Bad request

### Фактический результат
201 CREATED

**Comment by Valentina810** [comment]
Для date, theoryUrl, practiceUrl и homeworkUrl добавлены валидации. Поле topic может содержать любые символы

**Comment by Valentina810** [comment]
https://github.com/Valentina810/lms/pull/85
