### ISSUE TITLE
BUG-27 200 OK при передаче параметров типа string в виде number в запросе PATCH /users/{userId}/lessons/{lessonId}

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#54]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
major
### Предусловия
1) Отправить запрос POST /users
{
"name": "string",
"surname": "string",
"login": "string",
"password": "string",
"email": "string", //уникальный email
"dateBirth": "1999-09-14",
"avatarUrl": "string"
}

2) Отправить POST /users/{userId}/lessons запрос

{
"subject": {
"idSubject": 2
},
"topic": "Предлоги",
"date": "2023-09-14",
"timeStart": "09:40:00",
"timeEnd": "09:40:00",
"theoryUrl": "https://habr.com/ru/theoryUrl.htm",
"practiceUrl": "https://habr.com/ru/practiceUrl.htm",
"homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
"progress": 0,
"checkSuccessfully": false
}
### Шаги
Отправить запрос PATCH /users/{userId}/lessons/{lessonId}
{
    "subject": {
        "idSubject": 4
    },
    "topic": 123,
    "date": 123,
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": 123,
    "practiceUrl": 123,
    "homeworkUrl": 123,
    "progress": 100,
    "checkSuccessfully": true
}

curl --location --request PATCH 'http://195.161.68.231:8080/users/3/lessons/61' \
--header 'Content-Type: application/json' \
--data '{
    "subject": {
        "idSubject": 4
    },
    "topic": 123,
    "date": 123,
    "timeStart": "15:40:00",
    "timeEnd": "16:00:00",
    "theoryUrl": 123,
    "practiceUrl": 123,
    "homeworkUrl": 123,
    "progress": 100,
    "checkSuccessfully": true
}'

### Ожидаемый результат
400 Bad request

### Фактический результат
200 OK

**Comment by Valentina810** [comment]
Для date, theoryUrl, practiceUrl и homeworkUrl добавлены валидации. Поле topic может содержать любые символы

**Comment by Valentina810** [comment]
https://github.com/Valentina810/lms/pull/85
