### ISSUE TITLE
BUG-28 Некорректное сообщение при ошибке в JSON для запроса POST /users/{userId}/lessons

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#55]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.1
## URL стенда
http://195.161.68.231:8080 
## Приоритет
medium
## Критичность
minor
### Предусловия
 Отправить запрос POST /users
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "string", //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}
### Шаги
Отправить запрос POST /users/{userId}/lessons
{
    "subject": {
        "idSubject": 2
    },
    "topic": "Предлоги"
    "date": "2023-09-14"
    "timeStart": "09:40:00"
    "timeEnd": "09:40:00"
    "theoryUrl": "https://habr.com/ru/theoryUrl.htm"
    "practiceUrl": "https://habr.com/ru/practiceUrl.htm"
    "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
    "progress": 0,
    "checkSuccessfully": false
}

curl --location 'http://195.161.68.231:8080/users/3/lessons' \
--header 'Content-Type: application/json' \
--data '{
    "subject": {
        "idSubject": 2
    },
    "topic": "Предлоги"
    "date": "2023-09-14"
    "timeStart": "09:40:00"
    "timeEnd": "09:40:00"
    "theoryUrl": "https://habr.com/ru/theoryUrl.htm"
    "practiceUrl": "https://habr.com/ru/practiceUrl.htm"
    "homeworkUrl": "https://habr.com/ru/homeworkUrl.htm",
    "progress": 0,
    "checkSuccessfully": false
}'

### Ожидаемый результат
400 Bad request
{
"status": "BAD_REQUEST",
"message": "Неверная структура объекта: проверьте скобки, запятые и названия полей",
"date": "2023-09-11 19:06:04"
}

### Фактический результат
{
    "status": "BAD_REQUEST",
    "message": "JSON parse error: Unexpected character ('\"' (code 34)): was expecting comma to separate Object entries",
    "date": "2023-09-18 14:37:17"
}

**Comment by Valentina810** [comment]
Пофикшено https://github.com/Valentina810/lms/pull/43

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
