### ISSUE TITLE
BUG-30 idUser всех создаваемых пользователей равен 0 в запросе POST /users

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#90]
## Номер сборки
1.0.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
high
## Критичность
blocker

### Шаги
Отправить запрос POST /users на создание пользователя, в body указать
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "string",
  "email": "j@mail.ru" , //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

curl --location 'http://195.161.68.231:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "irinasav",
  "password": "TY89*tQW!k",
  "email": "irinasav111222@yandex.ru",
  "dateBirth": "2000-09-14",
  "avatarUrl": "https://habr.com/ru/irinasav.jpg"
}'

### Ожидаемый результат
201 OK, в ответе присваивается уникальный idUser
### Фактический результат
201 OK, в ответе присваивается idUser равный 0

**Comment by Valentina810** [comment]
Проблема в том что мапстракт не смог смаппить поля в сущности user из-за того что поле с Id называлась в объектах по-разному. Исправлено https://github.com/Valentina810/lms/pull/89
