### ISSUE TITLE
BUG-31 201 OK при передаче в password строки из пробелов в запросе POST /users

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#96]
## Номер сборки
1.0.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
high
## Критичность
critical
### Шаги
Отправить запрос POST /users на создание пользователя, в body указать
{
  "name": "string",
  "surname": "string",
  "login": "string",
  "password": "      ",
  "email": "j@mail.ru" , //уникальный email
  "dateBirth": "1999-09-14",
  "avatarUrl": "string"
}

curl --location 'http://195.161.68.231:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "Андрей",
"surname": "Савельева",
"login": "irinasav",
"password": "       ",
"email": "testemaill@gmai.com",
"dateBirth": "2000-09-14",
"avatarUrl": "https://habr.com/ru/irinasav.jpg"
}'

### Ожидаемый результат
400 BAD REQUEST
### Фактический результат
201 OK

**Comment by Valentina810** [comment]
@Yudiol ты конечно уволился уже с проекта, мы всё понимаем. Но техдолг-то сам себя не починит 

![Image](https://github.com/Valentina810/lms/assets/83814517/3eeb1850-c804-4eab-a410-7ac281012881)

добавишь аннотации  @NotBlank к обязательным полям?

**Comment by Yudiol** [comment]
Пока не уволился

**Comment by Valentina810** [comment]
Поправлено, версию 1.0.3 раскатили, можно тестировать

**Comment by janekomarovskaja** [comment]
Протестировано повторно, работает
