### ISSUE TITLE
BUG-32 Некорректное сообщение об ошибке при отправке 1001 символа в avatarUrl в запросе POST /users

### ISSUE THREAD

**Issue by janekomarovskaja** [Valentina810/lms#98]
## Номер спринта
1 (28.08.2023-17.09.2023)
## Номер сборки
1.0.1
## URL стенда
http://195.161.68.231:8080 

## Приоритет
low
## Критичность
trivial
### Шаги
Отправить запрос POST /users на создание пользователя, в body указать
{
  "name": "Ирина",
  "surname": "Савельева",
  "login": "login",
  "password": "password",
  "email": "emaill@gmail.com",
  "dateBirth": "1999-09-09",
  "avatarUrl": "https://habr.com/ru/testurltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturlvtesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltesturltes.jpg"
}

### Ожидаемый результат
В ответе указание ошибки
{
    "status": "BAD_REQUEST",
    "message": "Длина адреса должна быть не больше 1000 знаков; ",
    "date": "2023-10-02 18:08:45"
}
### Фактический результат
{
    "status": "BAD_REQUEST",
    "message": "Длина адреса должен быть не больше 1000 знаков; ",
    "date": "2023-10-02 18:08:45"
}

**Comment by Valentina810** [comment]
Поправлено, версию 1.0.3 раскатили, можно тестировать

**Comment by janekomarovskaja** [comment]
протестировано повторно, работает
